In [1]:
import numpy as np


In [5]:
#Here we want to show why a numpy array and fast and better than a list
my_arr = np.arange(1000000)


In [236]:
my_list = list(range(1000000))

In [238]:
 %time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 108 μs, sys: 2.16 ms, total: 2.27 ms
Wall time: 3.39 ms


In [240]:
%time for _ in range(10):my_list2 = [x*2 for x in my_list]

CPU times: user 230 ms, sys: 66.2 ms, total: 296 ms
Wall time: 301 ms


In [242]:
# how to make an array
data1 = np.array([1, 2, 3, 4 ,5 ])

In [244]:
# other way
data2 = [2 ,4, 5, 6]
arr2 = np.array(data2)

In [25]:
print(data1)

[1 2 3 4 5]


In [27]:
print(arr2)

[2 4 5 6]


In [29]:
#How to check the following of an array
# dimension 
data1.ndim

1

In [31]:
#How to check the data type
data1.dtype

dtype('int64')

In [33]:
#how to check the shape of the array
data1.shape


(5,)

In [48]:
#Nested sequences
data3 =[[1, 2, 3, 4],[5, 6, 7, 8]]
arr3 = np.array(data3)


In [52]:
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


In [62]:
arr3.dtype



dtype('int64')

In [60]:
arr3.shape

(2, 4)

In [ ]:
#Other functions to create arrays zeros and ones and empty e

In [74]:

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [86]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [80]:
# arange is an array-valued version of the built in python range function
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
# noteby difault the data type for numpy array creations is "float64"


In [90]:
# To convert an array from one dtype to another using "astype"
arr = np.array([1, 2, 3, 4]) 

In [92]:
arr.dtype

dtype('int64')

In [94]:
float_arr = arr.astype(np.float64)

In [98]:
float_arr.dtype

dtype('float64')

In [100]:
# in the above example integers were cast as floating point


In [108]:
my_arr = np.array([2.6, 3.4, -4.3, 5.9, 6.8])
                  

In [110]:
my_arr.dtype

dtype('float64')

In [120]:
my_arr_int = my_arr.astype(np.int64)
my_arr_int

array([ 2,  3, -4,  5,  6])

In [122]:
my_arr_int.dtype

dtype('int64')

In [126]:
# to covert array to strings
my_arr_strings = my_arr_int.astype(np.string_)
my_arr_strings

array([b'2', b'3', b'-4', b'5', b'6'], dtype='|S21')

In [130]:
my_arr_strings.dtype

dtype('S21')

In [132]:
#arithmaetic with NumPy arrays

In [138]:
arr4 = np.array([[1., 2., 3.], [4., 5., 6.,]])

In [141]:
arr4

array([[1., 2., 3.],
       [4., 5., 6.]])

In [143]:
arr4 * arr4

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [145]:
arr4 + arr4

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [147]:
arr4 - arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [149]:
1/arr4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [151]:
arr4**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [153]:
arr4.dtype

dtype('float64')

In [163]:
arr5 = np.array([[0., 4., 1.,], [7., 2., 12.]])
arr5
                 

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [161]:
arr4 > arr5

array([[ True, False,  True],
       [False,  True, False]])

In [165]:
#Basic indexing and slicing


In [177]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
arr6[5]

5

In [183]:
arr6[3:7]

array([3, 4, 5, 6])

In [185]:
#assigning a scalar value to a slice


In [204]:
arr6[3:7] = 100

In [206]:
arr6

array([  0,   1,   2, 100, 100, 100, 100,   7,   8,   9])

In [208]:
arr_slice = arr6[3:7]

In [210]:
arr_slice

array([100, 100, 100, 100])

In [212]:
arr6

array([  0,   1,   2, 100, 100, 100, 100,   7,   8,   9])

In [217]:
arr_slice[1] =200

In [219]:
arr6

array([  0,   1,   2, 100, 200, 100, 100,   7,   8,   9])

In [221]:
 arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [223]:
arr2d[0][2]

3

In [234]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])